# -*- coding: utf-8 -*-
"""4주차 실습

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nu-JkGfK3FeN6KFQZleK5hQt0Ohl3g2n
"""

import pandas as pd
import numpy as np
movies= pd.read_csv("movie.csv")
movie_acotor_director=movies[["actor_1_name",
                              "actor_2_name",
                              "actor_3_name"
                              , "director_name"]]

movie_acotor_director.head()

type(movies[["director_name"]])

type(movies["director_name"])

type(movies.loc[:,["director_name"]])

type(movies.loc[:,"director_name"])

cols= ["actor_1_name",
                              "actor_2_name",
                              "actor_3_name"
                              , "director_name"]

movie_acotor_director = movies[cols]

movies[                   [ "actor_1_name",
                              "actor_2_name",
                              "actor_3_name"
                              , "director_name"]]

movies=pd.read_csv("movie.csv")
def shorten(col):
  return(
      str(col)
      .replace("facebook_likes","fb")
      .replace("_for_reviews","") 
  )
movies=movies.rename(columns=shorten)
movies.dtypes.value_counts()

movies.select_dtypes(include="int").head()

movies.select_dtypes(include="number").head()

movies.select_dtypes(include=["int","object"]).head()

movies.select_dtypes(exclude="float").head()

movies.filter(like="fb").head()

movies.filter(items=cols).head()

movies.filter(regex=r"\d").head()

movies=pd.read_csv("movie.csv")
def shorten(col):
  return(
      str(col)
      .replace("facebook_likes","fb")
      .replace("_for_reviews","") 
  )
movies=movies.rename(columns=shorten)

movies.columns

cat_core=['movie_title','title_year','content_rating','genres']
cat_people=['director_name','actor_1_name','actor_2_name','actor_3_name']
cat_other=['color','country','language','plot_keywords','movie_imdb_link']
cont_fb=['director_fb','actor_1_fb','actor_2_fb','actor_3_fb','cast_total_fb','movie_fb']
cont_finance=['budget','gross']
cont_num_reviews=['num_voted_users','num_user','num_critic']
cont_other=['imdb_score','duration','aspect_ratio','facenumber_in_poster']

new_col_order=(
    cat_core
    +cat_people
    +cat_other
    +cont_fb
    +cont_finance
    +cont_num_reviews
    +cont_other
)

set(movies.columns) == set(new_col_order)

movies[new_col_order].head()

movies=pd.read_csv("movie.csv")
movies.shape

movies.size

movies.ndim

len(movies)

movies.count()

movies.min()

movies.describe().T

movies.describe(percentiles=[0.01,0.3,0.99]).T

movies.min(skipna=False)

colleges= pd.read_csv("college.csv")
colleges + 5

colleges= pd.read_csv("college.csv",index_col="INSTNM")

college_ugds=colleges.filter(like="UGDS_")
college_ugds.head()

name="Northwest-Shoals Community College"
college_ugds.loc[name]

college_ugds.loc[name].round(2)

(college_ugds.loc[name]+0.0001).round(2)

college_ugds + 0.00501

(college_ugds + 0.00501) // 0.01

college_ugds_op_round=((college_ugds + 0.00501) // 0.01 / 100)
college_ugds_op_round.head()

college_ugds_round = (college_ugds + 0.00001).round(2)
college_ugds_round

college_ugds_op_round.equals(college_ugds_round)

college2 = (
    college_ugds.add(0.00501).floordiv(0.01).div(100)
)
college2.equals(college_ugds_op_round)

np.nan == np.nan

None == None

college_ugds == 0.0019

college_self_compare = college_ugds == college_ugds
college_self_compare.head()

college_self_compare.all() #NaN이 있다.

(college_ugds == np.nan).sum()

college_ugds.isna().sum()

college_ugds.equals(college_ugds)

colleges= pd.read_csv("college.csv",index_col="INSTNM")
college_ugds=colleges.filter(like="UGDS_")
college_ugds.head()

college_ugds.count()

college_ugds.count(axis="columns").head()

college_ugds.count(axis=1).head()

college_ugds.sum(axis="columns").head()

college_ugds.sum(axis=1).head()

college_ugds.median(axis="index")

college_ugds_cumsum=college_ugds.cumsum(axis=1)
college_ugds_cumsum.head()